errorCode = 1
warningCode = 1
severity = "warning"

enableAllRules = true

# Disabled rules
[rule.file-header]
    Disabled = true
[rule.max-public-structs]
    Disabled = true
[rule.function-length]
    Disabled = true
[rule.add-constant]
    Disabled = true
[rule.exported]
    Disabled = true
[rule.banned-characters]
    Disabled = true
[rule.package-comments]
    Disabled = true

# Rule tuning
[rule.argument-limit]
    Arguments = [5]
[rule.cyclomatic]
    Arguments = [5]
[rule.function-result-limit]
    Arguments = [2]
[rule.line-length-limit]
    Arguments = [150]
[rule.cognitive-complexity]
    Arguments = [5]